services:
  - type: web
    name: mofet-dashboard
    env: python
    buildCommand: |
      export DISABLE_POETRY_INSTALL=1
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
